apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp
resources:
  - resources/namespace.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/ingress.yaml
  - resources/scaled-object.yaml
