controller:
  hostPort:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  nodeSelector:
    kubernetes.io/os: linux
    ingress-ready: "true"
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      effect: "NoSchedule"
