repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
- name: kube-prometheus-stack
  namespace: kube-prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
  version: 45.27.*
  wait: true
  values:
    - values/kube-prometheus-stack.yaml
